version: '3'

services:

  db:
    build:
      context: ./mysql
      dockerfile: dockerfile
    command: --innodb-use-native-aio=0
    container_name: db-container
    restart: always
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - desafio2-network

  app:
    build: 
      context: ./node
      dockerfile: dockerfile
    container_name: app-container
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh 
    command: node index.js
    networks: 
      - desafio2-network
    volumes: 
      - ./node:/usr/src/app
    depends_on: 
      - db
  
  nginx:
    build: 
      context: ./nginx
      dockerfile: dockerfile
    image: nginx-image
    container_name: nginx-container
    networks: 
      - desafio2-network
    ports: 
      - "8080:80"
    depends_on: 
      - app


networks: 
  desafio2-network:
    driver: bridge      